version: '3.7'

services:
  library-api:
    container_name: library-api
    image: library-api:latest
    ports:
      - 5533:80
    build:
      context: .
      args:
        - GIT_SHA
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Acceptance
      - ConnectionStrings__LibraryDB=Server=db;Database=Library;User Id=sa;Password=password123!;
  
  db:
    build:
      context: db
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: password123!
      MSSQL_DB: Library
    ports:
      - 1533:1433
