version: '3.7'

services:
  library-api:
    container_name: library-api
    image: library-api:latest
    ports:
      - 5000:80
    build:
      context: .
      dockerfile: Library.API/Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Acceptance
      - ConnectionStrings__LibraryDB=Server=db;Database=Library;User Id=libraryuser;Password=librarypassword123!;
  
  db:
    container_name: library-db
    build:
      context: db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: adminpassword123!
      MSSQL_DB: Library
      MSSQL_USER: libraryuser
      MSSQL_PASSWORD: librarypassword123!
    ports:
      - 1533:1433
