name: Pull Request

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Setup Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1

      - name: Verify
        run: make verify
        
      - name: Verify Infrastructure
        run: make setup-infra
        env:
          PULUMI_STACK: dev
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          IS_PR_WORKFLOW: true
