name: Verify

on:
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Verify
        run: make verify

      - name: Login to Github Docker
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Image
        run: |
          docker image tag library-api docker.pkg.github.com/${{ github.repository }}/library-api:latest
          docker image tag library-api docker.pkg.github.com/${{ github.repository }}/library-api:${{ github.sha }}

          docker push docker.pkg.github.com/${{ github.repository }}/library-api:latest
          docker push docker.pkg.github.com/${{ github.repository }}/library-api:${{ github.sha }}

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Setup Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1

      - name: Deploy Infrastructure
        run: make setup-infra
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          PULUMI_STACK: dev
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Web App Container Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ steps.deploy-infra.outputs.appServiceName }}
          app-settings-json: |
            [
                {
                    "name": "DOCKER_REGISTRY_SERVER_URL",
                    "value": "docker.pkg.github.com/${{ github.repository }}",
                    "slotSetting": false
                },
                {
                    "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                    "value": "${{ github.repository_owner }}",
                    "slotSetting": false
                },
                {
                    "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                    "value": "${{ secrets.LIBRARY_PAT }}",
                    "slotSetting": false
                }
            ]

      - name: Deploy Application to Dev
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.deploy-infra.outputs.appServiceName }}
          images: docker.pkg.github.com/${{ github.repository }}/library-api:${{ github.sha }}

      - name: Azure logout
        run: |
          az logout

      - name: Integration Tests
        run: make integration
        env:
          GIT_HASH: ${{ github.sha }}
