name: Verify

on:
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          tags: library-api:latest
          build-args: |
            GIT_SHA=${{ github.sha }}

      - name: Container Scanner
        uses: Azure/container-scan@v0
        with:
          image-name: library-api:latest

      - name: Verify
        run: make verify

      - name: Login to Github Docker
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Image
        run: |
          docker image tag library-api docker.pkg.github.com/${{ github.repository }}/library-api:latest
          docker image tag library-api docker.pkg.github.com/${{ github.repository }}/library-api:${{ github.sha }}

          docker push docker.pkg.github.com/${{ github.repository }}/library-api:latest
          docker push docker.pkg.github.com/${{ github.repository }}/library-api:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1

      - name: Deploy Infrastructure
        run: make setup-infra
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          DOCKER_REGISTRY_SERVER_URL: docker.pkg.github.com/${{ github.repository }}
          DOCKER_REGISTRY_SERVER_USERNAME: ${{ github.repository_owner }}
          DOCKER_REGISTRY_SERVER_PASSWORD: ${{ secrets.LIBRARY_PAT }}
          PULUMI_STACK: dev
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Application to Dev
        uses: azure/webapps-deploy@v2
        with:
          app-name: library-app
          images: docker.pkg.github.com/${{ github.repository }}/library-api:${{ github.sha }}

      - name: Azure logout
        run: |
          az logout

      - name: Integration Tests
        run: make integration
        env:
          GIT_SHA: ${{ github.sha }}
